### ISSUE TITLE
Basic SpringBoot Starter project

### ISSUE THREAD

**Issue by rajashekharms369** [rajashekharms369/Covid-19-Vaccination#1]
Description

## Todo
- [x] Generate Basic SpringBoot Starter project
- [x] Generate Required Entity Classes
- [x] Setup Project Logo and Name
